# Generated by Django 2.2.28 on 2024-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
